import { useState, useEffect } from 'react'
import { useApp } from '../context/AppContext'
import { api } from '../api'

// ─── HTML template ─────────────────────────────────────────────────────────────

function buildHtml({ meta, summary, findings, attackPaths, entities, sections }) {
  const ts = new Date().toLocaleString()
  const sevColor = { CRITICAL: '#c03030', HIGH: '#d97c14', MEDIUM: '#b8a020', LOW: '#2a7080' }
  const sevBg    = { CRITICAL: '#200808', HIGH: '#1e1000', MEDIUM: '#181400', LOW: '#081218' }

  function badge(sev) {
    const c = sevColor[sev] || '#666'; const b = sevBg[sev] || '#111'
    return `<span style="display:inline-block;padding:1px 7px;border-radius:2px;font-size:10px;font-weight:700;letter-spacing:.06em;background:${b};color:${c};border:1px solid ${c}40">${sev}</span>`
  }

  const findingsHtml = !sections.findings ? '' : `
  <section>
    <h2>Security Findings <span style="font-size:14px;font-weight:400;color:#888">(${findings.length})</span></h2>
    ${['CRITICAL','HIGH','MEDIUM','LOW'].map(sev => {
      const grp = findings.filter(f => f.severity === sev && !f.suppressed)
      if (!grp.length) return ''
      return `
      <details open>
        <summary style="cursor:pointer;padding:8px 0;font-size:13px;color:${sevColor[sev]}">${sev} &nbsp;·&nbsp; ${grp.length}</summary>
        <table>
          <thead><tr><th>Entity</th><th>Category</th><th>Message</th><th>Detected</th></tr></thead>
          <tbody>
            ${grp.map(f => `<tr>
              <td style="font-family:monospace;font-size:11px">${f.entity_arn || ''}</td>
              <td>${f.category || ''}</td>
              <td>${f.message || ''}</td>
              <td style="white-space:nowrap">${f.created_at ? new Date(f.created_at).toLocaleDateString() : ''}</td>
            </tr>`).join('')}
          </tbody>
        </table>
      </details>`
    }).join('')}
  </section>`

  const pathsHtml = !sections.paths ? '' : `
  <section>
    <h2>Attack Paths <span style="font-size:14px;font-weight:400;color:#888">(${attackPaths.length})</span></h2>
    <table>
      <thead><tr><th>Severity</th><th>From</th><th>Objective</th><th>Hops</th><th>Found</th></tr></thead>
      <tbody>
        ${attackPaths.map(p => `<tr>
          <td>${badge(p.severity)}</td>
          <td style="font-family:monospace;font-size:11px">${p.from_principal_arn || ''}</td>
          <td style="font-family:monospace;font-size:11px">${p.objective_value || p.objective_type || ''}</td>
          <td style="text-align:center">${p.total_hops || ''}</td>
          <td style="white-space:nowrap">${p.created_at ? new Date(p.created_at).toLocaleDateString() : ''}</td>
        </tr>`).join('')}
      </tbody>
    </table>
  </section>`

  const inventoryHtml = !sections.inventory ? '' : `
  <section>
    <h2>Entity Inventory <span style="font-size:14px;font-weight:400;color:#888">(${entities.length})</span></h2>
    <table>
      <thead><tr><th>Type</th><th>Name</th><th>ARN</th><th>Account</th></tr></thead>
      <tbody>
        ${entities.slice(0, 500).map(e => `<tr>
          <td style="text-transform:uppercase;font-size:10px;color:#888">${e.node_type || e.principal_type || ''}</td>
          <td>${e.label || (e.arn || '').split('/').pop()}</td>
          <td style="font-family:monospace;font-size:10px">${e.arn || e.node_id || ''}</td>
          <td style="font-family:monospace;font-size:10px">${e.account_id || ''}</td>
        </tr>`).join('')}
        ${entities.length > 500 ? `<tr><td colspan="4" style="color:#888;text-align:center">… and ${entities.length - 500} more</td></tr>` : ''}
      </tbody>
    </table>
  </section>`

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>WorstAssume Security Report – ${meta.date}</title>
<meta name="description" content="AWS security assessment report generated by WorstAssume">
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0 }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #09090b; color: #d0d0d8; font-size: 13px; line-height: 1.6; padding: 32px; }
  h1 { font-size: 28px; font-weight: 800; color: #fff; letter-spacing: -0.02em; }
  h2 { font-size: 16px; font-weight: 700; color: #fff; margin: 32px 0 12px; letter-spacing: -0.01em; border-bottom: 1px solid #222; padding-bottom: 8px; }
  header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 32px; border-bottom: 1px solid #222; padding-bottom: 24px; }
  header .meta { font-size: 11px; color: #888; margin-top: 4px; }
  .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 12px; margin: 16px 0 24px; }
  .stat-card { background: #111; border: 1px solid #222; border-radius: 4px; padding: 14px 16px; }
  .stat-val { font-size: 24px; font-weight: 800; color: #fff; font-variant-numeric: tabular-nums; }
  .stat-lbl { font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: #888; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: #888; padding: 6px 10px; border-bottom: 1px solid #222; }
  td { padding: 7px 10px; border-bottom: 1px solid #161618; color: #c0c0c8; }
  tr:hover td { background: #111; }
  details > summary { list-style: none; }
  details > summary::before { content: '▸ '; }
  details[open] > summary::before { content: '▾ '; }
  section { margin-bottom: 40px; }
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #222; font-size: 10px; color: #555; }
</style>
</head>
<body>
<header>
  <div>
    <h1>WorstAssume Security Report</h1>
    <div class="meta">Generated: ${ts} &nbsp;·&nbsp; Accounts: ${meta.accounts}</div>
  </div>
  <div style="text-align:right;font-size:11px;color:#888">${meta.date}</div>
</header>

${!sections.summary ? '' : `
<section>
  <h2>Executive Summary</h2>
  <div class="summary-grid">
    <div class="stat-card"><div class="stat-val" style="color:#c03030">${summary.critical}</div><div class="stat-lbl">Critical</div></div>
    <div class="stat-card"><div class="stat-val" style="color:#d97c14">${summary.high}</div><div class="stat-lbl">High</div></div>
    <div class="stat-card"><div class="stat-val" style="color:#b8a020">${summary.medium}</div><div class="stat-lbl">Medium</div></div>
    <div class="stat-card"><div class="stat-val" style="color:#2a7080">${summary.low}</div><div class="stat-lbl">Low</div></div>
    <div class="stat-card"><div class="stat-val">${summary.totalFindings}</div><div class="stat-lbl">Total Findings</div></div>
    <div class="stat-card"><div class="stat-val">${summary.totalPaths}</div><div class="stat-lbl">Attack Paths</div></div>
    <div class="stat-card"><div class="stat-val">${summary.totalEntities}</div><div class="stat-lbl">Entities</div></div>
  </div>
</section>`}

${findingsHtml}
${pathsHtml}
${inventoryHtml}

<footer>Generated by WorstAssume · ${ts}</footer>
</body>
</html>`
}

// ─── CSV ───────────────────────────────────────────────────────────────────────

function buildCsv(findings) {
  const esc = v => `"${String(v ?? '').replace(/"/g, '""')}"`
  const hdr = ['Severity','Category','Entity Type','Entity ARN','Message','Detected']
  const rows = findings.map(f => [
    f.severity,
    f.category,
    f.entity_type || f.principal_type || '',
    f.entity_arn  || f.principal_arn  || '',
    f.message || '',
    f.created_at ? new Date(f.created_at).toISOString() : '',
  ].map(esc).join(','))
  return [hdr.join(','), ...rows].join('\r\n')
}

// ─── Download helper ───────────────────────────────────────────────────────────

function download(content, filename, mime) {
  const blob = new Blob([content], { type: mime })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url; a.download = filename
  document.body.appendChild(a); a.click()
  setTimeout(() => { URL.revokeObjectURL(url); a.remove() }, 200)
}

// ─── Modal ─────────────────────────────────────────────────────────────────────

const FORMATS = [
  { id: 'html', label: '🌐 HTML (styled report)' },
  { id: 'json', label: '{ } JSON (machine-readable)' },
  { id: 'csv',  label: '📊 CSV  (findings only)' },
]

export default function ReportModal({ onClose }) {
  const { findings, entities, accounts } = useApp()

  const [format,      setFormat]      = useState('html')
  const [sections,    setSections]    = useState({ summary: true, findings: true, paths: true, inventory: true })
  const [attackPaths, setAttackPaths] = useState(null)
  const [pathsErr,    setPathsErr]    = useState(null)
  const [exporting,   setExporting]   = useState(false)

  // Lazy-load attack paths for preview count
  useEffect(() => {
    api.attackPaths()
      .then(d => setAttackPaths(Array.isArray(d) ? d : []))
      .catch(e => setPathsErr(e.message))
  }, [])

  const allFindings = (findings || []).filter(f => !f.suppressed)
  const allEntities = entities || []
  const allPaths    = attackPaths || []

  const summary = {
    critical:       allFindings.filter(f => f.severity === 'CRITICAL').length,
    high:           allFindings.filter(f => f.severity === 'HIGH').length,
    medium:         allFindings.filter(f => f.severity === 'MEDIUM').length,
    low:            allFindings.filter(f => f.severity === 'LOW').length,
    totalFindings:  allFindings.length,
    totalPaths:     allPaths.length,
    totalEntities:  allEntities.length,
  }

  const meta = {
    date:     new Date().toISOString().slice(0, 10),
    accounts: accounts.map(a => a.account_name || a.account_id).join(', ') || 'unknown',
    generated: new Date().toISOString(),
    tool:     'WorstAssume',
  }

  const dateSlug = meta.date

  function toggleSection(k) {
    setSections(s => ({ ...s, [k]: !s[k] }))
  }

  function doExport() {
    setExporting(true)
    try {
      if (format === 'json') {
        const payload = {
          meta,
          summary,
          ...(sections.findings  && { findings:    allFindings }),
          ...(sections.paths     && { attackPaths: allPaths }),
          ...(sections.inventory && { entities:    allEntities }),
        }
        download(JSON.stringify(payload, null, 2), `worstassume-report-${dateSlug}.json`, 'application/json')
      } else if (format === 'csv') {
        download(buildCsv(allFindings), `worstassume-findings-${dateSlug}.csv`, 'text/csv')
      } else {
        const html = buildHtml({ meta, summary, findings: allFindings, attackPaths: allPaths, entities: allEntities, sections })
        download(html, `worstassume-report-${dateSlug}.html`, 'text/html')
      }
      onClose()
    } finally {
      setExporting(false)
    }
  }

  const SECTION_LABELS = [
    { k: 'summary',   label: 'Executive Summary',    count: null },
    { k: 'findings',  label: 'Security Findings',    count: allFindings.length },
    { k: 'paths',     label: 'Attack Paths',         count: allPaths.length },
    { k: 'inventory', label: 'Entity Inventory',     count: allEntities.length },
  ]

  const csvOnly = format === 'csv'

  return (
    <>
      <div className="modal-backdrop" onClick={onClose} />
      <div className="modal" style={{ width: 420 }}>
        <div className="modal-header">
          <span className="modal-title">↓ Export Report</span>
          <button className="slideover-close" onClick={onClose}>✕</button>
        </div>

        <div className="modal-body" style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

          {/* Format */}
          <div>
            <div className="form-label">Format</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {FORMATS.map(f => (
                <label key={f.id} style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer', fontSize: 12, color: format === f.id ? 'var(--text)' : 'var(--text-dim)', padding: '7px 10px', borderRadius: 3, background: format === f.id ? 'var(--bg3)' : 'transparent', border: `1px solid ${format === f.id ? 'var(--amber)' : 'var(--border)'}`, transition: 'all .12s' }}>
                  <input type="radio" name="fmt" value={f.id} checked={format === f.id} onChange={() => setFormat(f.id)}
                    style={{ accentColor: 'var(--amber)' }} />
                  {f.label}
                </label>
              ))}
            </div>
          </div>

          {/* Sections (hidden for CSV) */}
          {!csvOnly && (
            <div>
              <div className="form-label">Include sections</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                {SECTION_LABELS.map(({ k, label, count }) => (
                  <label key={k} style={{ display:'flex', alignItems:'center', gap:10, cursor:'pointer', fontSize:12, color:'var(--text-dim)', padding:'6px 10px', borderRadius:3, background:'var(--bg2)', border:'1px solid var(--border)', opacity: sections[k] ? 1 : 0.5, transition:'opacity .12s' }}>
                    <input type="checkbox" checked={sections[k]} onChange={() => toggleSection(k)}
                      style={{ accentColor:'var(--amber)' }} />
                    <span style={{ flex:1 }}>{label}</span>
                    {count !== null && (
                      <span style={{ fontSize:10, color:'var(--text-faint)', fontFamily:'IBM Plex Mono' }}>{count}</span>
                    )}
                  </label>
                ))}
              </div>
              {attackPaths === null && !pathsErr && (
                <div style={{ fontSize:10, color:'var(--text-faint)', marginTop:6, display:'flex', alignItems:'center', gap:6 }}>
                  <span className="spinner-ring" style={{ width:10, height:10, borderWidth:2 }} /> Loading attack paths…
                </div>
              )}
              {pathsErr && (
                <div style={{ fontSize:10, color:'var(--amber)', marginTop:6 }}>⚠ Could not load attack paths: {pathsErr}</div>
              )}
            </div>
          )}

          {/* Preview */}
          <div style={{ background:'var(--bg2)', border:'1px solid var(--border)', borderRadius:3, padding:'10px 12px', fontSize:11, color:'var(--text-dim)' }}>
            <div style={{ marginBottom:6, fontSize:10, textTransform:'uppercase', letterSpacing:'.08em', color:'var(--text-faint)' }}>File preview</div>
            {format === 'csv'
              ? <span style={{ fontFamily:'IBM Plex Mono' }}>worstassume-findings-{dateSlug}.csv &nbsp;·&nbsp; {allFindings.length} rows</span>
              : <span style={{ fontFamily:'IBM Plex Mono' }}>worstassume-report-{dateSlug}.{format} &nbsp;·&nbsp; {
                  Object.entries(sections).filter(([,v]) => v).map(([k]) => k).join(', ')
                }</span>
            }
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn secondary sm" onClick={onClose}>Cancel</button>
          <button className="btn primary sm" disabled={exporting} onClick={doExport}>
            {exporting ? <><span className="spinner-ring" style={{width:12,height:12,borderWidth:2}} /> Exporting…</> : '↓ Export'}
          </button>
        </div>
      </div>
    </>
  )
}
